---
title: "EcoWorm_Networks_Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
CAK10n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAK10n_Network.csv', header=T, stringsAsFactors=T)

CAK5n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAK5n_Network.csv', header=T, stringsAsFactors=T)

CAK10y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAK10y_Network.csv', header=T, stringsAsFactors=T)

CAK5y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAK5y_Network.csv', header=T, stringsAsFactors=T)


CAX10n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAX10n_Network.csv', header=T, stringsAsFactors=T)

CAX5n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAX5n_Network.csv', header=T, stringsAsFactors=T)

CAX10y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAX10y_Network.csv', header=T, stringsAsFactors=T)

CAX5y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/CAX5y_Network.csv', header=T, stringsAsFactors=T)



USA10n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/USA10n_Network.csv', header=T, stringsAsFactors=T)

USA5n_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/USA5n_Network.csv', header=T, stringsAsFactors=T)

USA10y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/USA10y_Network.csv', header=T, stringsAsFactors=T)

USA5y_Network<-read.csv('D:/Backup/Projekte/Github/Wormland/USA5y_Network.csv', header=T, stringsAsFactors=T)


##much better, read the files in in a loop

###we want to sort our networks, only p values that are loewer than 0.05 (or, if we like 0.01 should be considered, -if- the pvalue (column 5) is lower than this, we need col 1,2 and 3)
setwd('D:/Backup/Projekte/Github/Wormland/')

#files = system('ls *Network.csv', intern = T)

files = list.files(pattern="*Network.csv")

for ( i in 1:length(files)){
  name = gsub(pattern = '_Network.csv', 
              replacement = '',
              x = files[i])
  ### Filter the data in the loop
  x = read.csv(files[i])
  x = x[,c(1:3,5)]
  x$wTO_sign = ifelse(x$pval_sig< 0.05, x$wTO_sign, 0)
  assign(name, x)
}

require(wTO)
NetVis(Node.1 = USA10n$Node.1, Node.2 = USA10n$Node.2,
       wTO = USA10n$wTO_sign, pval = USA10n$pval_sig, 
       MakeGroups = 'louvain', cutoff = list(kind = "Threshold", value = 0.1))


require(igraph)
g <- graph_from_data_frame(USA10n)
V(g)$size=3
E(g)$weight=3
plot(g, vertex.label=NA)


sw <- sample_smallworld(g)

plot(sw, vertex.size=6, vertex.label=NA, layout=layout_in_circle)


```


```{r}
Ecoworm<-read.csv("D:\\Backup\\Projekte/Github/Wormland/EcoW-Tax-Tree.csv", header=T, stringsAsFactors=TRUE, sep=";")

head(Ecoworm)

tr <- make_tree(Ecoworm[,1], children=Ecoworm[,2:3], mode = "undirected")

plot(tr, vertex.size=10, vertex.label=NA) 





```


